name: CDK Typescript CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths: [ "cdk-typescript/**" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "cdk-typescript/**" ]
    
jobs:
  build-cdk:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup CDK
      run: bash ./ci/cdk-validate-integ-tests.sh cdk-typescript